# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [3]:
chipo['item_price_'] = chipo['item_price'].apply(lambda x: float(x[1:]))
# Otra forma: 
# chipo['item_price_'] = pd.to_numeric(chipo['item_price'].astype(str).str.replace("$", ""))
chipo['unit_price'] = chipo['item_price_'] / chipo['quantity']
# chipo.loc[chipo['unit_price'].idxmax(), 'item_name']
chipo.loc[(chipo['unit_price'] == chipo['unit_price'].max()), 'item_name'].drop_duplicates().values

array(['Steak Salad Bowl', 'Carnitas Salad Bowl', 'Barbacoa Salad Bowl'],
      dtype=object)

### Step 4. How many products cost more than $10.00?

In [4]:
chipo.loc[(chipo['unit_price'] > 10), 'item_name'].nunique()

25

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [5]:
print(chipo.loc[(chipo['unit_price'] > 10), 'order_id'].nunique())
print('No es lo mismo.')

787
No es lo mismo.

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [6]:
chipo_costes_pedidos = chipo.groupby('order_id')['item_price_'].sum()
# chipo_pedidos_m10 = chipo_costes_pedidos[(chipo_costes_pedidos['item_price_'] > 15)]
print(len(chipo_costes_pedidos[chipo_costes_pedidos > 10]))
print(chipo_costes_pedidos[chipo_costes_pedidos > 10].shape[0])
print('No es lo mismo.')

1834
1834
No es lo mismo.

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [7]:
print(chipo.loc[(chipo['item_price_'] > 10), 'order_id'].nunique())
print('No es lo mismo.')

863
No es lo mismo.

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [53]:
# Hecho en paso 3: 
# chipo['unit_price'] = chipo['item_price_'] / chipo['quantity']

# Paso 5: 
# chipo[['item_name','unit_price']]
chipo_precios_productos = chipo.drop_duplicates(subset=['item_name', 'unit_price'])[['item_name', 'unit_price']]
chipo_precios_productos

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
3989                          Chicken Salad        8.19
4235                           Chicken Bowl        8.50
4237                    Chips and Guacamole        4.25
4509                                  Chips        1.99
4510                          Barbacoa Bowl       11.49

[139 rows x 2 columns]

### Step 6. Sort by the name of the item

In [54]:
chipo_precios_productos.sort_values('item_name')

              item_name  unit_price
298   6 Pack Soft Drink        6.49
4510      Barbacoa Bowl       11.49
471       Barbacoa Bowl       11.48
115       Barbacoa Bowl        8.99
39        Barbacoa Bowl       11.75
...                 ...         ...
186   Veggie Salad Bowl       11.25
960   Veggie Salad Bowl        8.75
1395  Veggie Soft Tacos        8.49
738   Veggie Soft Tacos       11.25
781   Veggie Soft Tacos        8.75

[139 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [55]:
# 1. 
print(chipo.loc[(chipo['item_price_'] == chipo['item_price_'].max()), 'quantity'].values)
print()
# 2. 
print(chipo.loc[chipo['item_price_'].idxmax(), 'quantity'])

[15]

15

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [56]:
print(len(chipo[(chipo['item_name'] == 'Veggie Salad Bowl')]))
# Para obtener el nº total de unidades de este producto que se pidió (puede ser que en algunos pedidos se pida más de una)
print(chipo.loc[chipo['item_name'] == "Veggie Salad Bowl", "quantity"].sum())

18
18

### Step 9. How many times did someone order more than one Canned Soda?

In [57]:
len(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1.1)])

20